default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types: [python]
        description: "Ruff code formatter"

      - id: ruff-check
        name: ruff-check
        description: "Ruff code checker"
        entry: uv run ruff check --force-exclude
        args: [--fix, --exit-non-zero-on-fix]
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: python .pre-commit-run.py mypy
        types: [python]
        language: system
        require_serial: true
        pass_filenames: true

      - id: pytest
        name: pytest
        entry: python .pre-commit-run.py pytest
        types: [python]
        language: system
        require_serial: true
